### ISSUE TITLE
Tracking issue for project direction

### ISSUE THREAD

**Issue by markods** [markods/GpuSeqAlign#1]
This is a tracking issue for the general direction of the project.

- [x] Rework coop algorithms to be multi-launch.
  - [x] gpu3-ml-diagdiag 
  - [x] gpu4-ml-diagdiag2pass
- [x] Implement gpu7-mlsp-diagdiag.
- [x] Implement gpu8-mlsp-diagdiag.
- [x] Implement gpu9-mlsp-diagdiagdiag.
- [x] Rework existing benchmarking framework.
  - [x] Rework json config file format.
  - [ ] ~Implement GpuSeqAlign genetic algorithm parameter optimization.~
- [ ] ~Add zig build script for external tools.~
  - [ ] ~Fetch and build CudaSW++4.0 [1](https://github.com/asbschmidt/CUDASW4) [2](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-024-05965-6).~
  - [ ] ~Fetch swissp database.~
  - [ ] ~Run CudaSW++ on swissp using the provided query file.~
  - [ ] ~Similarly for blast, clustal_omega, emboss_needle, mafft.~
- [ ] ~Convert PowerShell build script into zig build script.~
  - [ ] ~Build cuda files with nvcc, and pass zig as c/c++ compiler.~
  - [ ] ~Support building on Windows and Linux.~
  - [ ] ~Build separate executable for each algorithm.~
  - [ ] ~Run GpuSeqAlign tests.~
- [ ] Rework algorithms to give the same results as CudaSW++ 3.0 [1](https://cudasw.sourceforge.net/homepage.htm#latest).
  - [ ] ~Read from standard file formats.~
  - [ ] Rework algorithms to use Affine-Gap penalty.
  - [ ] ~Replace Needleman-Wunsch with Smith-Waterman.~
    - [ ] ~Rename Nw* prefix to Sa* (Sequence Alignment).~
  - [ ] ~(Optional) See if it's possible to reintroduce Needleman-Wunsch without losing performance, copying code, making the code unreadable or difficult to debug.~
- [ ] Verify and optimize existing implementations with Nsight [1](https://developer.nvidia.com/blog/improving-gpu-performance-by-reducing-instruction-cache-misses-2/).
  - [x] Rework existing gpu implementations to limit the number of launched kernels using cudaOccupancyMaxPotentialBlockSize.
  - [ ] Use Nsight Compute to profile kernels.
  - [ ] ~Look into using Hyperfine/Poop on Linux for measuring time.~
  - [ ] ~(Optional) Look into using Coz on Linux for measuring time.~
- [ ] ~(Optional) Implement gpu10-mlsppt-diagdiagdiagskew.~

**Comment by markods** [comment]
Tracked elsewhere.
